name: flutter_weather
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0
  google_fonts: ^2.1.0
  hydrated_bloc: ^8.0.0
  json_annotation: ^4.0.0
  path_provider: ^2.0.3
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.0
  build_runner: ^1.10.0
  json_serializable: ^4.0.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
